# Generated by Django 4.1 on 2024-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Lender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_payment', models.CharField(max_length=10)),
                ('AmountLent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('ExpirationDate', models.DateTimeField(auto_now_add=True)),
                ('TotalAmountDue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Active', models.BooleanField(default=True)),
                ('id_Customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Customer.customer')),
                ('id_Lender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Lender.lender')),
            ],
            options={
                'db_table': 'Loans',
            },
        ),
    ]
