# Generated by Django 4.1 on 2024-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoL', models.CharField(max_length=10)),
                ('HiringDate', models.DateTimeField(auto_now_add=True)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Active', models.BooleanField(default=True)),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Person.person')),
            ],
            options={
                'db_table': 'Lender',
            },
        ),
    ]
