# Generated by Django 4.1 on 2024-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PaymentFrecuency', '0001_initial'),
        ('Loans', '0001_initial'),
        ('PaymentStatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Payment', models.CharField(max_length=10)),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('AmountPerPayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PendingAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Active', models.BooleanField(default=True)),
                ('id_Loans', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Loans.loans')),
                ('id_PayFrecuency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PaymentFrecuency.paymentfrequency')),
                ('id_payStatus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='PaymentStatus.paymentstatus')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
