# Generated by Django 4.1 on 2024-11-18 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeAlerts', models.IntegerField()),
                ('AlertDate', models.DateTimeField(null=True)),
                ('MessegaAlert', models.CharField(max_length=225)),
                ('Active', models.BooleanField(default=True)),
                ('id_Loans', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Loans.loans')),
            ],
            options={
                'db_table': 'Alerts',
            },
        ),
    ]
