# Generated by Django 4.1 on 2024-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdentityCard', models.CharField(max_length=16)),
                ('Address', models.CharField(max_length=200)),
                ('FirtsName', models.CharField(max_length=50)),
                ('SecondName', models.CharField(max_length=50)),
                ('FirsLastName', models.CharField(max_length=50)),
                ('SecondLantName', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
    ]
